### PR TITLE
MLOPS 349: Seldon storage initializer image and values.yaml

### PR DESCRIPTION
**Pull request by bernardolk**
I have moved the set value from main.tf to the values.yaml file and added a different image to the storageInitializer thing, so that we don't have to change it after deploying using `kubectl get configmaps -n seldon`

### CODE REVIEW

**Comment by bernardolk** [comment]
Needs to be tested and a review

**Comment by tvinagre** [comment]
What's this `storageInitializer` for? Didn't get it

**Review by tvinagre — APPROVED** [review]

**Comment by bernardolk** [comment]
> What's this `storageInitializer` for? Didn't get it

That's something we had to update manually before, not sure what it is for, but maybe @pipatth or @carloszanella can explain it better

**Comment by carloszanella** [comment]
@bernardolk @tvinagre 
https://docs.seldon.io/projects/seldon-core/en/v1.6.0/servers/overview.html#init-containers

**Pull request merged**
